version: 2

build:
  method: dockerfile

environment:
  - name: PYTHONUNBUFFERED
    value: "1"
  - name: PYTHONDONTWRITEBYTECODE
    value: "1"
  - name: PORT
    value: "3000"
  - name: POSTGRES_USER
    value: "postgres"
  - name: POSTGRES_PASSWORD
    value: "postgres"
  - name: POSTGRES_DB
    value: "mydb"
  - name: POSTGRES_PORT
    value: "5432"
  # For Coolify deployments, this will be replaced with the actual database service hostname
  - name: POSTGRES_HOST
    value: "host.docker.internal"
  - name: APP_NAME
    value: "FastAPI REST API with Tortoise ORM"
  - name: APP_VERSION
    value: "1.0.0"
  - name: APP_DESCRIPTION
    value: "A RESTful API built with FastAPI and Tortoise ORM for deployment on Hetzner with Coolify"

publish:
  - name: API
    port: 3000
    protocol: http

health:
  path: /health
  port: 3000 