version: 2

build:
  command: pip install -r requirements.txt

start:
  command: python start.py

environment:
  - name: PYTHONUNBUFFERED
    value: "1"
  - name: PYTHONDONTWRITEBYTECODE
    value: "1"
  - name: ENVIRONMENT
    value: "production"
  - name: PORT
    value: "80"

publish:
  - name: API
    port: 80
    protocol: http

health:
  path: /health
  port: 80 