version: '3'

services:
  api:
    build: .
    ports:
      - "${API_PORT:-8080}:${CONTAINER_PORT:-8000}"
    volumes:
      - .:/app
    environment:
      - DEBUG=1
      - PORT=${CONTAINER_PORT:-8000}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${CONTAINER_PORT:-8000}/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s 