version: '3'

services:
  api:
    build: .
    ports:
      - "${API_PORT}:${PORT}"
    environment:
      - PORT=${PORT}
      - APP_MODULE=app.main:app
    env_file:
      - .env
    depends_on:
      - postgres
    restart: always

  postgres:
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    restart: always

volumes:
  postgres_data: 