version: '3'

services:
  api:
    build: .
    ports:
      - "${API_PORT:-8080}:${PORT:-8000}"
    environment:
      - PORT=${PORT:-8000}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${PORT:-8000}/health"]
      interval: 30s
      timeout: 10s
      retries: 3 